/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CommunityWriteRouteImport } from './routes/community-write'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitySearchRouteImport } from './routes/activity-search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItineraryTripIdRouteImport } from './routes/itinerary.$tripId'
import { Route as TripTripIdStopStopIdRouteImport } from './routes/trip.$tripId.stop.$stopId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWriteRoute = CommunityWriteRouteImport.update({
  id: '/community-write',
  path: '/community-write',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitySearchRoute = ActivitySearchRouteImport.update({
  id: '/activity-search',
  path: '/activity-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryTripIdRoute = ItineraryTripIdRouteImport.update({
  id: '/itinerary/$tripId',
  path: '/itinerary/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdStopStopIdRoute = TripTripIdStopStopIdRouteImport.update({
  id: '/trip/$tripId/stop/$stopId',
  path: '/trip/$tripId/stop/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-search': typeof ActivitySearchRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/community-write': typeof CommunityWriteRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/plan-trip': typeof PlanTripRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/itinerary/$tripId': typeof ItineraryTripIdRoute
  '/trip/$tripId/stop/$stopId': typeof TripTripIdStopStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-search': typeof ActivitySearchRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/community-write': typeof CommunityWriteRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/plan-trip': typeof PlanTripRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/itinerary/$tripId': typeof ItineraryTripIdRoute
  '/trip/$tripId/stop/$stopId': typeof TripTripIdStopStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-search': typeof ActivitySearchRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/community-write': typeof CommunityWriteRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/plan-trip': typeof PlanTripRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/itinerary/$tripId': typeof ItineraryTripIdRoute
  '/trip/$tripId/stop/$stopId': typeof TripTripIdStopStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-search'
    | '/admin'
    | '/community'
    | '/community-write'
    | '/expenses'
    | '/login'
    | '/my-trips'
    | '/notes'
    | '/packing'
    | '/plan-trip'
    | '/profile'
    | '/signup'
    | '/itinerary/$tripId'
    | '/trip/$tripId/stop/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-search'
    | '/admin'
    | '/community'
    | '/community-write'
    | '/expenses'
    | '/login'
    | '/my-trips'
    | '/notes'
    | '/packing'
    | '/plan-trip'
    | '/profile'
    | '/signup'
    | '/itinerary/$tripId'
    | '/trip/$tripId/stop/$stopId'
  id:
    | '__root__'
    | '/'
    | '/activity-search'
    | '/admin'
    | '/community'
    | '/community-write'
    | '/expenses'
    | '/login'
    | '/my-trips'
    | '/notes'
    | '/packing'
    | '/plan-trip'
    | '/profile'
    | '/signup'
    | '/itinerary/$tripId'
    | '/trip/$tripId/stop/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitySearchRoute: typeof ActivitySearchRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  CommunityWriteRoute: typeof CommunityWriteRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  MyTripsRoute: typeof MyTripsRoute
  NotesRoute: typeof NotesRoute
  PackingRoute: typeof PackingRoute
  PlanTripRoute: typeof PlanTripRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ItineraryTripIdRoute: typeof ItineraryTripIdRoute
  TripTripIdStopStopIdRoute: typeof TripTripIdStopStopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-write': {
      id: '/community-write'
      path: '/community-write'
      fullPath: '/community-write'
      preLoaderRoute: typeof CommunityWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-search': {
      id: '/activity-search'
      path: '/activity-search'
      fullPath: '/activity-search'
      preLoaderRoute: typeof ActivitySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$tripId': {
      id: '/itinerary/$tripId'
      path: '/itinerary/$tripId'
      fullPath: '/itinerary/$tripId'
      preLoaderRoute: typeof ItineraryTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/stop/$stopId': {
      id: '/trip/$tripId/stop/$stopId'
      path: '/trip/$tripId/stop/$stopId'
      fullPath: '/trip/$tripId/stop/$stopId'
      preLoaderRoute: typeof TripTripIdStopStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitySearchRoute: ActivitySearchRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  CommunityWriteRoute: CommunityWriteRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  MyTripsRoute: MyTripsRoute,
  NotesRoute: NotesRoute,
  PackingRoute: PackingRoute,
  PlanTripRoute: PlanTripRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ItineraryTripIdRoute: ItineraryTripIdRoute,
  TripTripIdStopStopIdRoute: TripTripIdStopStopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
